apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-service
  namespace: mysql
spec:
  selector:
    app: mysql-exporter
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
